language: c
dist: trusty
sudo: required
os: linux
compiler: gcc

branches:
  only:
  - master

env:
  global:
    - OWTRAVIS_BUILD_REPO_SLUG=open-watcom/travis-ci-ow-builds
    - OWTRAVIS_BUILD_DIR=${HOME}/build/$OWTRAVIS_BUILD_REPO_SLUG
    - OWTRAVIS_LOGS_REPO_SLUG=open-watcom/travis-ci-logs
    - OWTRAVIS_LOGS_DIR=${HOME}/build/$OWTRAVIS_LOGS_REPO_SLUG
    - OWROOT=$TRAVIS_BUILD_DIR
    #
    - OWOBJDIR=binbuild
    - OWRELROOT=$OWROOT/test
    - OWTRAVISDIR=$OWROOT/travis
    - OWDISTRDIR=$OWROOT/distrib
    - OWSRCDIR=$OWROOT/bld
    - OWBINDIR=$OWROOT/build/$OWOBJDIR
    - OWDOCSDIR=$OWROOT/docs
    #
    - OWBRANCH_SF=sourceforge
    - OWVERBOSE=0
    - OWDISTRBUILD=0
    - OWDOCBUILD=0
    - OWDOCQUIET=1
    - CP_OPTS=-Rnv

cache:
  directories:
    - $OWBINDIR
    - $OWSRCDIR/watcom/$OWOBJDIR
    - $OWROOT/test
    - $OWROOT/buildx

before_script:
    # get environment/cache info if debug is active
    - $OWTRAVISDIR/envinfo.sh

after_failure:
    # after failure transfer log files back to GitHub repository
    - $OWTRAVISDIR/gitupdf.sh

after_success:
    # after success transfer OW build to GitHub repository
    - $OWTRAVISDIR/gitupds.sh

jobs:
  allow_failures:
    - os: windows
  include:
    #################################
    - stage: Mirror
      name: "Mirror master branch commits to SF"
      if: type = push
      git:
        depth: false
      cache: false
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
      script:
        # update SF mirror
        - $OWTRAVISDIR/gitusf.sh
    #################################
    - stage: Bootstrap
      name: "Build minimal set of build tools Linux"
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=GCC
        - export OWVERBOSE=1
        # clear cache
        - $OWTRAVISDIR/cacheclr.sh
      install:
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/buildx.sh
    #################################
    - stage: Build1
      name: "OW tools build Linux"
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=GCC
      install:
        # install DOS Emulator
        - sudo apt-get install -y dosemu
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/buildx.sh
      before_cache:
        - $OWTRAVISDIR/cache3.sh save
    #################################
    - stage: Update build
      name: "Update Build Linux"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=GCC
      install:
        - . $OWROOT/cmnvars.sh
      script:
        - true
    #################################
    - stage: Tests
      name: "Test wasm assembler"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISTEST=WASM
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C compiler"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISTEST=C
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test FORTRAN 77 compiler"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISTEST=F77
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C++ compiler"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISTEST=CXX
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    - # ...
      name: "Test C run-time library"
      if: type = push
      before_install:
        # configure Git client
        - git config --global user.email "openwatcomtravis@gmail.com"
        - git config --global user.name "Open Watcom Travis"
        - git config --global push.default simple
        # set environmet variable
        - export OWTOOLS=WATCOM
        - export OWTRAVISTEST=CRTL
      install:
        - export WATCOM=$OWROOT/test
        - export PATH=$WATCOM/binl:$PATH
        - export INCLUDE=$WATCOM/lh
        - unset LIB
        - . $OWROOT/cmnvars.sh
      script:
        - $OWTRAVISDIR/test.sh
    #################################
    - stage: Clear cache
      name: "Delete build cache Linux"
      script:
        - $OWTRAVISDIR/cacheclr.sh
    #################################
