# Pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "10 1 * * *"
  displayName: "Daily midnight build"
  branches:
    include:
    - master

resources:
  repositories:
  - repository: wikidocsgit
    type: GitHub
    name: open-watcom/open-watcom-v2-webdocs
    endpoint: open-watcom-v2-wikidocs

variables: 
  owroot:           $(Build.SourcesDirectory)
  owobjdir:         binbuild
  owaskpass:        $(Pipeline.Workspace)/askpass.sh

  owimage_lnx:      'ubuntu-latest'
  owimage_nt:       'vs2017-win2016'
  owimage_osx:      'macOS-latest'
  owtools_lnx:      GCC
  owtools_nt:       VISUALC
  owtools_osx:      CLANG
  owscript_lnx:     ci/buildx.sh
  owscript_nt:      ci\buildx.cmd
  owscript_osx:     ci/buildx.sh
  owarch_lnx:       lnx
  owarch_nt:        nt
  owarch_osx:       osx
  owartifactfile:   owartifact.tar.gz
  owartifactfile7z: owartifact.tar
  owcibin:          $(owroot)\ci\bin64

stages:
  - stage: start
    displayName: "Start"
    jobs:
      - job: start
        steps:
        - checkout: none
  - stage: mirror
    displayName: "Mirror OW repository"
    dependsOn:
      - start
    condition: >
      and(
        succeeded(), 
        in( variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual' )
      )
    jobs:
      - job: mirror
        displayName: "Mirror to SF"
        variables:
          owarch:   ${{ variables.owarch_lnx }}
          owimage:  ${{ variables.owimage_lnx }}
          owsfproject: openwatcom/open-watcom-v2-test
        pool:
          vmImage:  $(owimage)
        steps:
        - template: ci/mirror.yml
  - stage: boot
    displayName: "Bootstrap"
    dependsOn:
      - start
    jobs:
      - job: boot
        displayName: "Bootstrap"
        variables:
          owbuild.stage:    boot
        strategy:
          matrix:
            Linux:
              owarch:       ${{ variables.owarch_lnx }}
              owimage:      ${{ variables.owimage_lnx }}
              owtools:      ${{ variables.owtools_lnx }}
              owscript:     ${{ variables.owscript_lnx }}
            Windows:
              owarch:       ${{ variables.owarch_nt }}
              owimage:      ${{ variables.owimage_nt }}
              owtools:      ${{ variables.owtools_nt }}
              owscript:     ${{ variables.owscript_nt }}
            OSX:
              owarch:       ${{ variables.owarch_osx }}
              owimage:      ${{ variables.owimage_osx }}
              owtools:      ${{ variables.owtools_osx }}
              owscript:     ${{ variables.owscript_osx }}
        pool:
          vmImage: $(owimage)
        steps:
        - script: $(owscript)
          displayName: "Bootstrap"
        - template: ci/artfsave.yml
          parameters: 
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
        - template: ci/artfsave.yml
          parameters: 
            path:       bld/watcom/$(owobjdir)
            artfname:   bld-watcom-$(owarch)
  - stage: build
    displayName: "Build"
    dependsOn:
      - boot
    jobs:
      - job: build
        displayName: "Build"
        variables:
          owbuild.stage:    build
        strategy:
          matrix:
            Linux:
              owarch:       ${{ variables.owarch_lnx }}
              owimage:      ${{ variables.owimage_lnx }}
              owtools:      ${{ variables.owtools_lnx }}
              owscript:     ${{ variables.owscript_lnx }}
            Windows:
              owarch:       ${{ variables.owarch_nt }}
              owimage:      ${{ variables.owimage_nt }}
              owtools:      ${{ variables.owtools_nt }}
              owscript:     ${{ variables.owscript_nt }}
            OSX:
              owarch:       ${{ variables.owarch_osx }}
              owimage:      ${{ variables.owimage_osx }}
              owtools:      ${{ variables.owtools_osx }}
              owscript:     ${{ variables.owscript_osx }}
        pool:
          vmImage: $(owimage)
        timeoutInMinutes: 90
        steps:
        - template: ci/dosbox.yml
        - template: ci/artfload.yml
          parameters:
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
        - template: ci/artfload.yml
          parameters:
            path:       bld/watcom/$(owobjdir)
            artfname:   bld-watcom-$(owarch)
        - script: $(owscript)
          displayName: "Build"
        - template: ci/artfsave.yml
          parameters: 
            path:       rel
            artfname:   rel-$(owarch)
            cond:       in( variables.owarch, variables.owarch_lnx, variables.owarch_nt )
        - template: ci/artfsave.yml
          parameters: 
            path:       bld/setupgui
            artfname:   bld-setupgui-$(owarch)
            cond:       in( variables.owarch, variables.owarch_lnx, variables.owarch_nt )
  - stage: tests
    displayName: "Tests"
    dependsOn:
      - build
    jobs:
      - job: tests
        displayName: "Tests"
        strategy:
          matrix:
            Linux:
              owarch:       ${{ variables.owarch_lnx }}
              owimage:      ${{ variables.owimage_lnx }}
              owtools:      ${{ variables.owtools_lnx }}
              owscript:     ${{ variables.owscript_lnx }}
            Windows:
              owarch:       ${{ variables.owarch_nt }}
              owimage:      ${{ variables.owimage_nt }}
              owtools:      ${{ variables.owtools_nt }}
              owscript:     ${{ variables.owscript_nt }}
        pool:
          vmImage: $(owimage)
        steps:
        - template: ci/artfload.yml
          parameters:
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
  - stage: docs
    displayName: "Documentation Build"
    dependsOn:
      - boot
    jobs:
      - job: docs
        displayName: "Documentation Build"
        variables:
          owarch:           ${{ variables.owarch_nt }}
          owimage:          ${{ variables.owimage_nt }}
          owtools:          ${{ variables.owtools_nt }}
          owscript:         ${{ variables.owscript_nt }}
          owbuild.stage:    docs
        strategy:
          matrix:
            DOS:
              owdoctarget: docdos
            Html:
              owdoctarget: dochtmlhelp
            NT:
              owdoctarget: docnt
            OS2:
              owdoctarget: docos2
            PDF:
              owdoctarget: docpdf
            WIN:
              owdoctarget: docwin
        pool:
          vmImage: $(owimage)
        steps:
        - template: ci/artfload.yml
          parameters:
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
        - script: $(owscript)
          displayName: "Documentation Build"
        - task: PublishPipelineArtifact@1
          displayName: "Save Artifact rel-$(owdoctarget)"
          inputs: 
            artifactName: "rel-$(owdoctarget)"
            targetPath: $(owroot)/rel
  - stage: instal
    displayName: "Installers Build"
    dependsOn:
      - docs
      - tests
    #condition: >
    #  and(
    #    succeeded(), 
    #    in( variables['Build.Reason'], 'Schedule', 'Manual' )
    #  )
    jobs:
      - job: instal
        displayName: "Installers Build"
        variables:
          owbuild.stage:    inst
        strategy:
          matrix:
            Linux:
              owarch:       ${{ variables.owarch_lnx }}
              owimage:      ${{ variables.owimage_lnx }}
              owtools:      ${{ variables.owtools_lnx }}
              owscript:     ${{ variables.owscript_lnx }}
            Windows:
              owarch:       ${{ variables.owarch_nt }}
              owimage:      ${{ variables.owimage_nt }}
              owtools:      ${{ variables.owtools_nt }}
              owscript:     ${{ variables.owscript_nt }}
        pool:
          vmImage: $(owimage)
        steps:
        - template: ci/artfload.yml
          parameters:
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
        - template: ci/artfload.yml
          parameters:
            path:       bld/watcom/$(owobjdir)
            artfname:   bld-watcom-$(owarch)
        - template: ci/artfload.yml
          parameters:
            path:       bld/setupgui
            artfname:   bld-setupgui-$(owarch_nt)
        - template: ci/artfload.yml
          parameters:
            path:       bld/setupgui
            artfname:   bld-setupgui-$(owarch_lnx)
        # consolidate binaries
        - template: ci/artfload.yml
          parameters:
            path:       rel
            artfname:   rel-$(owarch_nt)
        - template: ci/artfload.yml
          parameters:
            path:       rel
            artfname:   rel-$(owarch_lnx)
        # consolidate documentation
        - template: ci/docload.yml
          parameters: {owdoctarget: docdos}
        - template: ci/docload.yml
          parameters: {owdoctarget: dochtmlhelp}
        - template: ci/docload.yml
          parameters: {owdoctarget: docnt}
        - template: ci/docload.yml
          parameters: {owdoctarget: docos2}
        - template: ci/docload.yml
          parameters: {owdoctarget: docpdf}
        - template: ci/docload.yml
          parameters: {owdoctarget: docwin}
        # run build script
        - script: $(owscript)
          displayName: "Build Installers"
        # create full binary archive
        - task: ArchiveFiles@2
          condition: in( variables.owarch, variables.owarch_lnx )
          inputs:
            rootFolderOrFile: '$(owroot)/rel'
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(owroot)/distrib/ow/bin/ow-snapshot.tar.gz'
            replaceExistingArchive: true
        # save all artifacts for distribution
        - template: ci/artfsave.yml
          parameters: 
            path:       distrib/ow/bin
            artfname:   distrib-$(owarch)
  - stage: release
    displayName: "GitHub Release"
    dependsOn:
      - instal
    #condition: >
    #  and(
    #    succeeded(), 
    #    in( variables['Build.Reason'], 'Schedule', 'Manual' )
    #  )
    jobs:
      - job: release
        displayName: "GitHub Release"
        variables:
          owarch:       ${{ variables.owarch_lnx }}
          owimage:      ${{ variables.owimage_lnx }}
          owtools:      ${{ variables.owtools_lnx }}
          owtag:        Current-build
        pool:
          vmImage:      $(owimage)
        steps:
        - template: ci/gituser.yml
        - checkout: self
          persistCredentials: true
        - template: ci/artfload.yml
          parameters:
            path:       build/$(owobjdir)
            artfname:   build-$(owarch)
        - template: ci/artfload.yml
          parameters:
            path:       distrib/ow/bin
            artfname:   distrib-$(owarch_nt)
        - template: ci/artfload.yml
          parameters:
            path:       distrib/ow/bin
            artfname:   distrib-$(owarch_lnx)
        - bash: echo "##vso[task.setvariable variable=owtagstamp;]$(date +'%Y-%m-%d %H:%M:%S')"
          displayName: "Get current timestamp"
        - bash: echo "##vso[task.setvariable variable=owgitstamp;]`git ls-remote --tags . | sed -n -e \"s:\([0-9a-z]*\) *refs/tags/${{ variables.owtag }}^{}:\1:p\"`"
          displayName: "Get 'Current-build' tag commit"
        - script: |
            if [ ! "$OWGITSTAMP" = "$BUILD_SOURCEVERSION" ]; then
              git tag -d $OWTAG
              git push --delete origin $OWTAG
              git tag -a -m "$OWTAGSTAMP" $OWTAG $BUILD_SOURCEVERSION
              git push origin $OWTAG
            else
              echo "##vso[task.setvariable variable=owtagstamp;]`git tag -l --format='%(contents)' $OWTAG`"
            fi
          displayName: "Recreate 'Current-build' tag"
        - task: GitHubRelease@0
          name: releasedel
          displayName: "Delete Release"
          continueOnError: true
          inputs:
            gitHubConnection: 'open-watcom-v2-releases'
            action: 'delete'
            tag: '$(owtag)'
        - task: GitHubRelease@0
          name: releaseadd
          displayName: "Add Release"
          condition: succeededOrFailed()
          inputs:
            gitHubConnection: 'open-watcom-v2-releases'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'manual'
            tag: '$(owtag)'
            title: '$(owtag)'
            releaseNotesSource: 'input'
            releaseNotes: 'Last updated $(owtagstamp)'
            assets: |
              distrib/ow/bin/open-watcom-*
              distrib/ow/bin/ow-snapshot.tar.gz
            isPreRelease: true
            addChangeLog: false
  - stage: scan
    displayName: "Coverity Scan"
    dependsOn:
      - tests
    #condition: >
    #  and(
    #    succeeded(), 
    #    in( variables['Build.Reason'], 'Schedule', 'Manual') 
    #  )
    jobs:
      - job: scan
        displayName: "Coverity Scan"
        timeoutInMinutes: 240
        variables:
          owcoverity.project:  open-watcom/open-watcom-v2
          owcoverity.tool.cmd: ''
        strategy:
          matrix:
            Linux:
              owarch:       ${{ variables.owarch_lnx }}
              owimage:      ${{ variables.owimage_lnx }}
              owtools:      ${{ variables.owtools_lnx }}
              owscript:     $(owroot)/ci/coverity.sh
              owcoverity.tool.src: linux64
              owcoverity.tool.archive: /tmp/cov-analysis-linux.tgz
              owcoverity.tool.base: /tmp/coverity-scan-analysis
              owcoverity.script: $(owroot)/ci/covbuild.sh
              owcoverity.results.archive: open-watcom-v2.tgz
            #Windows:
              #owarch:      ${{ variables.owarch_nt }}
              #owimage:     ${{ variables.owimage_nt }}
              #owtools:     ${{ variables.owtools_nt }}
              #owscript:    $(owroot)\ci\coverity.cmd
              #owcoverity.tool.src: win64
              #owcoverity.tool.archive: $(TEMP)\cov-analysis-windows.zip
              #owcoverity.tool.base: $(TEMP)\coverity-scan-analysis
              #owcoverity.script: $(owroot)\ci\covbuild.cmd
              #owcoverity.results.archive: open-watcom-v2.zip
        pool:
          vmImage: $(owimage)
        steps:
          - template: ci/coverity.yml
  - stage: wikidocs
    displayName: "Wiki Docs Build"
    dependsOn:
      - docs
    jobs:
      - job: wikidocs
        displayName: "Wiki Documentation Build"
        variables:
          owbuild.stage:    docs
          owarch:           ${{ variables.owarch_lnx }}
          owimage:          ${{ variables.owimage_lnx }}
          owtools:          ${{ variables.owtools_lnx }}
          owscript:         ${{ variables.owscript_lnx }}
        strategy:
          matrix:
            Html:
              owdoctarget:  wikihtml .and wikihtml .or -- -- docset=wikihtml
              owartifname:  wiki-dochtml
            PDF:
              owdoctarget:  wikipdf .and wikipdf .or -- -- docset=wikipdf
              owartifname:  wiki-docpdf
        pool:
          vmImage: $(owimage)
        steps:
        - template: ci/dosbox.yml
        - template: ci/wikibld.yml
          parameters:
            owartfname:     build-$(owarch)
            owpdf:          eq(variables.owartifname, 'wiki-docpdf')
  - stage: wikiupd
    displayName: "Wiki Docs Update"
    dependsOn:
      - wikidocs
    jobs:
      - job: wikiupd
        displayName: "Wiki Documentation Update"
        continueOnError: true
        variables:
          owarch:           ${{ variables.owarch_lnx }}
          owimage:          ${{ variables.owimage_lnx }}
          owtools:          ${{ variables.owtools_lnx }}
          owscript:         ${{ variables.owscript_lnx }}
          owwiki_depth:     10
          owwikiproject:    jmalak/open-watcom-v2-webdocs
          owwikipath:       wiki
          owwikiroot:       $(Pipeline.Workspace)/$(owwikipath)
          owwikiartfpath:   $(owwikiroot)/docs
        pool:
          vmImage: $(owimage)
        steps:
        - template: ci/wikiupd.yml
