# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables: 
  System.Debug: true
  owimage_lnx:  'ubuntu-latest'
  owimage_nt:   'vs2017-win2016'
  owimage_osx:  'macOS-latest'
  owobjdir_lnx: binlnx
  owobjdir_nt:  binnt
  owobjdir_osx: binosx
  owtools_lnx:  GCC
  owtools_nt:   VISUALC
  owtools_osx:  CLANG
  owscript_lnx: buildx.sh
  owscript_nt:  buildx.cmd
  owscript_osx: buildx.sh
  owarch_lnx:   lnx
  owarch_nt:    nt
  owarch_osx:   osx

schedules:
- cron: "0 1 * * *"
  displayName: Daily build
  branches:
    include:
    - master

trigger:
- master

pr:
  branches:
    include: 
    - master

stages:
  - stage: boot
    displayName: "Bootstrap"
    jobs:
      - job: Bootstrap
        strategy:
          matrix:
            Linux:
              owarch:   ${{ variables.owarch_lnx }}
              owobjdir: ${{ variables.owobjdir_lnx }}
              owimage:  ${{ variables.owimage_lnx }}
              owtools:  ${{ variables.owtools_lnx }}
              owscript: ${{ variables.owscript_lnx }}
            Windows:
              owarch:   ${{ variables.owarch_nt }}
              owobjdir: ${{ variables.owobjdir_nt }}
              owimage:  ${{ variables.owimage_nt }}
              owtools:  ${{ variables.owtools_nt }}
              owscript: ${{ variables.owscript_nt }}
            OSX:
              owarch:   ${{ variables.owarch_osx }}
              owobjdir: ${{ variables.owobjdir_osx }}
              owimage:  ${{ variables.owimage_osx }}
              owtools:  ${{ variables.owtools_osx }}
              owscript: ${{ variables.owscript_osx }}
        pool:
          vmImage: $(owimage)
        steps:
        - script: echo Build Reason = $(Build.Reason)
        - script: azure/$(owscript)
          displayName: "Bootstrap"
          env:
            OWAZURE_STAGE_NAME: boot
            OWOBJDIR: $(owobjdir)
            OWTOOLS: $(owtools)
        - template: azure/artifsav.yml
  - stage: build
    displayName: "Build"
    dependsOn: boot
    jobs:
      - job: Build
        strategy:
          matrix:
            Linux:
              owarch:   ${{ variables.owarch_lnx }}
              owobjdir: ${{ variables.owobjdir_lnx }}
              owimage:  ${{ variables.owimage_lnx }}
              owtools:  ${{ variables.owtools_lnx }}
              owscript: ${{ variables.owscript_lnx }}
            Windows:
              owarch:   ${{ variables.owarch_nt }}
              owobjdir: ${{ variables.owobjdir_nt }}
              owimage:  ${{ variables.owimage_nt }}
              owtools:  ${{ variables.owtools_nt }}
              owscript: ${{ variables.owscript_nt }}
            OSX:
              owarch:   ${{ variables.owarch_osx }}
              owobjdir: ${{ variables.owobjdir_osx }}
              owimage:  ${{ variables.owimage_osx }}
              owtools:  ${{ variables.owtools_osx }}
              owscript: ${{ variables.owscript_osx }}
        pool:
          vmImage: $(owimage)
        timeoutInMinutes: 90
        steps:
        - template: azure/artiflod.yml
        - script: sudo apt-get install -y dosbox
          displayName: "Install DOSBOX Linux"
          condition: in( variables.owarch, variables.owarch_lnx )
        - script: brew install dosbox
          displayName: "Install DOSBOX OSX"
          condition: in( variables.owarch, variables.owarch_osx )
        - script: azure/$(owscript)
          displayName: "Build"
          env: 
            OWAZURE_STAGE_NAME: build
            OWOBJDIR: $(owobjdir)
            OWTOOLS: $(owtools)
        - template: azure/relsave.yml
        - template: azure/instsave.yml
  - stage: tests
    displayName: "Tests"
    dependsOn: build
    condition: >
      and(succeeded(), 
      in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Schedule'))
    jobs:
      - job: Linux
        strategy:
          matrix:
            Linux:
              owarch:   ${{ variables.owarch_lnx }}
              owobjdir: ${{ variables.owobjdir_lnx }}
              owimage:  ${{ variables.owimage_lnx }}
              owtools:  ${{ variables.owtools_lnx }}
              owscript: ${{ variables.owscript_lnx }}
            Windows:
              owarch:   ${{ variables.owarch_nt }}
              owobjdir: ${{ variables.owobjdir_nt }}
              owimage:  ${{ variables.owimage_nt }}
              owtools:  ${{ variables.owtools_nt }}
              owscript: ${{ variables.owscript_nt }}
        pool:
          vmImage: $(owimage)
        steps:
        - template: azure/artiflod.yml
  - stage: docs
    displayName: "Documentation Build"
    dependsOn: boot
    condition: >
      and(succeeded(), 
      in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Schedule'))
    jobs:
      - job: Documentation
        variables:
          owarch: $(owarch_nt)
          owobjdir: $(owobjdir_nt)
        strategy:
          matrix:
            DOS:
              target: dos
              doctarget: docdos
            Html:
              target: htmlhelp
              doctarget: dochtml
            NT:
              target: nt
              doctarget: docnt
            OS2:
              target: os2
              doctarget: docos2
            PDF:
              target: pdf
              doctarget: docpdf
            WIN:
              target: win
              doctarget: docwin
        pool:
          vmImage: $(owimage_nt)
        steps:
        - template: azure/artiflod.yml
        - script: azure/$(owscript_nt)
          displayName: "Documentation Build"
          env:
            OWAZURE_STAGE_NAME: docs
            OWDOCTARGET: $(target)
            OWOBJDIR: $(owobjdir_nt)
            OWTOOLS: VISUALC
        - template: azure/relsave.yml
          parameters: {owobjdir: $(doctarget)}
  - stage: update
    displayName: "Consolidate Build"
    dependsOn: 
      - docs
      - tests
    jobs:
      - job: Linux
        variables:
          owarch: $(owarch_lnx)
        pool:
          vmImage: $(owimage_lnx)
        steps:
        # consolidate binaries
        - template: azure/relload.yml
          parameters: {owobjdir: $(owobjdir_lnx)}
        - template: azure/relload.yml
          parameters: {owobjdir: $(owobjdir_nt)}
        # consolidate documentation
        - template: azure/relload.yml
          parameters: {owobjdir: docdos}
        - template: azure/relload.yml
          parameters: {owobjdir: dochtml}
        - template: azure/relload.yml
          parameters: {owobjdir: docnt}
        - template: azure/relload.yml
          parameters: {owobjdir: docos2}
        - template: azure/relload.yml
          parameters: {owobjdir: docpdf}
        - template: azure/relload.yml
          parameters: {owobjdir: docwin}
        # complete OW release artifact
        - template: azure/relsave.yml
          parameters: {owobjdir: binall}
  - stage: instal
    displayName: "Build Installers"
    dependsOn: update
    condition: >
      and(succeeded(), 
      in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Schedule'))
    jobs:
      - job: installer
        strategy:
          matrix:
            Linux:
              owarch:   ${{ variables.owarch_lnx }}
              owobjdir: ${{ variables.owobjdir_lnx }}
              owimage:  ${{ variables.owimage_lnx }}
              owtools:  ${{ variables.owtools_lnx }}
              owscript: ${{ variables.owscript_lnx }}
            Windows:
              owarch:   ${{ variables.owarch_nt }}
              owobjdir: ${{ variables.owobjdir_nt }}
              owimage:  ${{ variables.owimage_nt }}
              owtools:  ${{ variables.owtools_nt }}
              owscript: ${{ variables.owscript_nt }}
        pool:
          vmImage: $(owimage)
        steps:
        - template: azure/artiflod.yml
        - template: azure/instload.yml
          parameters: {owobjdir: $(owobjdir_lnx)}
        - template: azure/instload.yml
          parameters: {owobjdir: $(owobjdir_nt)}
        - template: azure/relload.yml
          parameters: {owobjdir: binall}
        - script: azure/$(owscript)
          displayName: "Build Installers"
          env:
            OWAZURE_STAGE_NAME: inst
            OWOBJDIR: $(owobjdir)
            OWTOOLS: $(owtools)
        - template: azure/distsave.yml
  - stage: release
    displayName: "Make Release on GitHub"
    condition: >
      and(succeeded(), 
      in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Schedule'))
    jobs:
      - job: Linux
        variables:
          owarch: $(owarch_lnx)
        pool:
          vmImage: $(owimage_lnx)
        steps:
        - template: azure/artiflod.yml
          parameters: {owobjdir: $(owobjdir_lnx)}
        - template: azure/distload.yml
          parameters: {owobjdir: $(owobjdir_lnx)}
        - template: azure/distload.yml
          parameters: {owobjdir: $(owobjdir_nt)}
        - template: azure/distsave.yml
          parameters: {owobjdir: binall}
#        - task: GitHubRelease@0
#          inputs:
#            gitHubConnection: 
#            repositoryName: '$(Build.Repository.Name)' 
#            action: 'create' # Options: create, edit, delete
#            target: 'Current-build' # Required when action == Create || Action == Edit
#            tagSource: 'auto' # Required when action == Create# Options: auto, manual
#            #tagPattern: # Optional
#            #tag: # Required when action == Edit || Action == Delete || TagSource == Manual
#            #title: # Optional
#            #releaseNotesSource: 'file' # Optional. Options: file, input
#            #releaseNotesFile: # Optional
#            #releaseNotes: # Optional
#            assets: 'distrib/ow/bin/*' # Optional
#            assetUploadMode: 'replace' # Optional. Options: delete, replace
#            isDraft: false # Optional
#            isPreRelease: true # Optional
#            #addChangeLog: true # Optional
#            #compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
#            #releaseTag: # Required when compareWith == LastReleaseByTag
