variables: 
  owroot:           $(Build.SourcesDirectory)
  owobjdir:         binbuild
  owaskpass:        $(Pipeline.Workspace)/askpass.sh

  owimage_lnx:      'ubuntu-latest'
  owimage_nt:       'vs2017-win2016'
  owimage_osx:      'macOS-latest'
  owtools_lnx:      GCC
  owtools_nt:       VISUALC
  owtools_osx:      CLANG
  owscript_lnx:     ci/buildx.sh
  owscript_nt:      ci\buildx.cmd
  owscript_osx:     ci/buildx.sh
  owarch_lnx:       lnx
  owarch_nt:        nt
  owarch_osx:       osx
  owartifactfile:   owartifact.tar.gz
  owartifactfile7z: owartifact.tar
  owcibin:          $(owroot)\ci\bin64

jobs:
  - job: mirror
    displayName: "Mirror to SF"
    variables:
      owarch:   ${{ variables.owarch_lnx }}
      owimage:  ${{ variables.owimage_lnx }}
      owsfproject: openwatcom/open-watcom-v2-test-jm
    pool:
      vmImage:  $(owimage)
    steps:
    - template: ci/mirror.yml
  - job: wikiupd
    displayName: "Wiki Documentation Update"
    continueOnError: true
    variables:
      owroot:        $(Build.SourcesDirectory)
      owwiki_depth:  10
      owwikiroot:    $(Pipeline.Workspace)/wiki
      owaskpass:     $(Pipeline.Workspace)/askpass.sh
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ci/gituser.yml
    - template: ci/askpass.yml
    - script: |
        git clone --depth=1 --branch=master $(owwikiproto)$OWGHUSER@$(owwikihost)/$(owwikiproject).git $(owwikiroot)
        cd $(owwikiroot)
        git add -v -f .
        git status -uno --porcelain
        if [ -n "$(git status -uno --porcelain)x" ]
        then
          git commit -v -m "Azure Pipelines build $(Build.BuildNumber)"
          git push -v
        fi
        pwd
      displayName: "Wiki Docs update"
      env:
        SSH_PASSWORD: $(owghtoken2)
        OWGHUSER:     $(owghtoken1)
        SSH_ASKPASS:  $(owaskpass)
