resources:
  repositories:
  - repository: wikidocsgit
    type: GitHub
    name: open-watcom/open-watcom-v2-webdocs
    endpoint: open-watcom-v2-wikidocs

jobs:
  - job: wikiupd
    displayName: "Wiki Documentation Update"
    continueOnError: true
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ci/gituser.yml
    - checkout: wikidocsgit
      persistCredentials: true
      path: wiki
