# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables: 
  System.Debug: true
  owimage_lnx:  'ubuntu-latest'
  owimage_nt:   'vs2017-win2016'
  owimage_osx:  'macOS-latest'
  owobjdir_lnx: binlnx
  owobjdir_nt:  binnt
  owobjdir_osx: binosx
  owtools_lnx:  GCC
  owtools_nt:   VISUALC
  owtools_osx:  CLANG
  owscript_lnx: buildx.sh
  owscript_nt:  buildx.cmd
  owscript_osx: buildx.sh
  owarch_lnx:   lnx
  owarch_nt:    nt
  owarch_osx:   osx

trigger:
- master

stages:
  - stage: release
    displayName: "GitHub Release"
    jobs:
    - job: release
      displayName: "GitHub Release"
      variables:
        owarch: $(owarch_lnx)
        owtag: Current-build
        owtagstamp: ''
      pool:
        vmImage: $(owimage_lnx)
      steps:
      - task: GitHubRelease@0
        displayName: "Remove Release"
        inputs:
          gitHubConnection: 'open-watcom-v2-releases'
          repositoryName: '$(Build.Repository.Name)'
          action: 'delete'
          tag: '$(owtag)'
      - task: GitHubRelease@0
        displayName: "Add Release"
        condition: always()
        inputs:
          gitHubConnection: 'open-watcom-v2-releases'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'manual'
          tag: '$(owtag) $(owtagstamp)'
          title: '$(owtag)'
          assets: 'test.yml'
          isPreRelease: true
          addChangeLog: false
