# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "10 1 * * *"
  displayName: "Daily midnight build"
  branches:
    include:
    - master

resources:
  repositories:
  - repository: wikidocsgit
    type: GitHub
    name: open-watcom/open-watcom-v2-webdocs
    endpoint: open-watcom-v2-wikidocs

variables: 
  owroot:           $(Build.SourcesDirectory)
  owobjdir:         binbuild

  owimage_lnx:      'ubuntu-latest'
  owimage_nt:       'vs2017-win2016'
  owimage_osx:      'macOS-latest'

jobs:
  - job: wikiupd
    displayName: "Wiki Documentation Update"
    continueOnError: true
    variables:
      owimage:          ${{ variables.owimage_lnx }}
    pool:
      vmImage: $(owimage)
    steps:
    - template: ci/gituser.yml
    - checkout: wikidocsgit
      persistCredentials: true
      path: wiki
