resources:
  repositories:
  - repository: wiki
    type: GitHub
    name: open-watcom/open-watcom-v2-webdocs
    endpoint: open-watcom-v2-wikidocs

jobs:
  - job: wikiupd
    displayName: "Wiki Documentation Update"
    continueOnError: true
    variables:
      owwiki_depth:  10
      owwikiproject: open-watcom/open-watcom-v2-webdocs
      owwikiroot:    $(Pipeline.Workspace)/wiki
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: ci/gituser.yml
    - checkout: self
      persistCredentials: true
    - script: |
        set -x
        env | sort
        git config --get-all http.https://github.com/$(owwikiproject).extraheader
        git config http.https://github.com/$(owwikiproject).extraheader "AUTHORIZATION: basic ***"
        git clone --depth=1 --branch=master https://$(github.user)@github.com/$(owwikiproject).git $(owwikiroot)
        pwd
    - script: |
        set -x
        pwd
        cd $(owwikiroot)
        git add -v -f .
        git status -uno --porcelain
        if [ -n "$(git status -uno --porcelain)x" ]
        then
          git commit -v -m "Azure Pipelines build $(Build.BuildNumber)"
          git push -v
        fi
        pwd
      displayName: "Wiki Docs update"
