resources:
  repositories:
  - repository: wiki
    type: GitHub
    name: open-watcom/open-watcom-v2-webdocs
    endpoint: open-watcom-v2-wikidocs

jobs:
  - job: wikiupd
    displayName: "Wiki Documentation Update"
    continueOnError: true
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      persistCredentials: true
    - checkout: wiki
      persistCredentials: true
      path: wiki
