stages:
  - stage: wikidocs
    displayName: "Wiki Docs Build"
    dependsOn:
      - docs
    jobs:
      - job: WikiDocs
        variables:
          owarch: $(owarch_nt)
          owobjdir: ${{ variables.owobjdir_nt }}
          owtools: ${{ variables.owtools_nt }}
        strategy:
          matrix:
            Wiki Html:
              owdoctarget: wikihtml .and wikihtml .or -- -- docset=wikihtml
              owartifname: wiki-dochtml
            Wiki PDF:
              owdoctarget: wikipdf .and wikipdf .or -- -- docset=wikipdf
              owartifname: wiki-docpdf
        pool:
          vmImage: $(owimage_nt)
        steps:
        - template: bootload.yml
        - script: $(owscript_nt)
          displayName: "Documentation Build"
          env:
            OWBUILD_STAGE: docs
        - script: |
            xcopy docs\html\*.htm $(Build.ArtifactStagingDirectory)\
            xcopy docs\html\*.bmp $(Build.ArtifactStagingDirectory)\
            ren $(Build.ArtifactStagingDirectory)\*.htm *.html
            xcopy docs\pdf\*.pdf $(Build.ArtifactStagingDirectory)\
          displayName: "Copy Artifact Wiki files"
        - task: PublishPipelineArtifact@1
          displayName: "Save Artifact $(owartifname)"
          inputs: 
            artifactName: "$(owartifname)"
            targetPath: $(Build.ArtifactStagingDirectory)
  - stage: Wiki
    displayName: "Wiki Docs Update"
    dependsOn:
      - wikidocs
    #condition: >
    #  and(
    #    succeeded(), 
    #    in(variables['Build.Reason'], 'Schedule')
    #  )
    jobs:
      - job: wiki
        displayName: "Wiki Documentation Update"
        variables:
          owwiki_depth:  10
          owwikiproject: open-watcom/open-watcom-v2-webdocs
          owwikiroot:    $(Pipeline.Workspace)\wiki
        pool:
          vmImage: $(owimage_nt)
        steps:
        - checkout: self
          persistCredentials: true
        - script: |
            # configure Git client
            git config --global user.email "openwatcomazure@gmail.com"
            git config --global user.name "Open Watcom Azure"
            # get latest OW sources
            git clone --depth=1 --branch=master https://github.com/$(owwikiproject).git $(owwikiroot)
          displayName: "Wiki Docs clone"
        - task: DownloadPipelineArtifact@2
          displayName: "Load Artifact wiki-dochtml"
          inputs: 
            buildType:    'current'
            artifactName: "wiki-dochtml"
            targetPath:   $(owwikiroot)\docs
        - task: DownloadPipelineArtifact@2
          displayName: "Load Artifact wiki-docpdf"
          inputs: 
            buildType:    'current'
            artifactName: "wiki-docpdf"
            targetPath:   $(owwikiroot)\docs
        - script: |
            cd $(owwikiroot)
            git add -v -f .
            if [ -n "$(git status -uno --porcelain)" ]; then
              git commit -v -m "Azure Pipelines build $(Build.BuildNumber)"
              git checkout -b temp
              git checkout master
              git merge temp
              git branch -d temp
              git push -v
            fi
          displayName: "Wiki Docs update"
