name: Mirror

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo clone
      uses: actions/checkout@v1
    - name: GitHub checkout master
      run: |
          pwd
          git checkout master
    - name: Mirror to SourceForge
      run: |
          pwd
          cd $GITHUB_WORKSPACE
          pwd
          git remote set-url --push origin $OWSFPROTO$OWSFUSER@$OWSFHOST/p/$OWSFREPO
          git push -v
      env:
        SSH_PASSWORD: ${{ secrets.OW_SF_TOKEN2 }}
        OWSFUSER:     ${{ secrets.OW_SF_TOKEN1 }}
        OWSFPROTO:    https://
        OWSFHOST:     git.code.sf.net
        OWSFREPO:     openwatcom/open-watcom-v2-test
        GIT_ASKPASS:  ci/askpass.sh
