name: Mirror

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mirror
      run: |
          set -x
          cd $GITHUB_WORKSPACE
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          export SSH_PASSWORD=$OW_SF_TOKEN2
          export SSH_ASKPASS=ci/askpass.sh
          export GIT_ASKPASS=ci/askpass.sh
          git checkout master
          git remote set-url --push origin https://git.code.sf.net/p/openwatcom/open-watcom-v2-test
          git config credential.username $OW_SF_TOKEN1
          git push -v
      env:
        OW_SF_TOKEN1: ${{ secrets.OW_SF_TOKEN1 }}
        OW_SF_TOKEN2: ${{ secrets.OW_SF_TOKEN2 }}
