name: Mirror

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mirror
      run: |
          set -x
          cd $GITHUB_WORKSPACE
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          #export DISPLAY=:0
          export GIT_ASKPASS=ci/askpass.sh
          export SSH_PASSWORD=$OW_SF_TOKEN2
          git checkout master
          git remote set-url origin https://$OW_SF_TOKEN1@git.code.sf.net/p/openwatcom/open-watcom-v2-test
          git push -v
      env:
        OW_SF_TOKEN1: ${{ secrets.OW_SF_TOKEN1 }}
        OW_SF_TOKEN2: ${{ secrets.OW_SF_TOKEN2 }}
