name: Mirror

on: [push]

jobs:
  build:
    name: Mirror to SourceForge
    runs-on: ubuntu-latest
    steps:
    - name: OW Repo clone
      uses: actions/checkout@v1
    - name: Checkout master branch
      run: git checkout master
    - name: Prepare askpass script
      run: |
        echo "echo \"\$SSH_PASSWORD\"" > $HOME/askpass.sh
        chmod +x $HOME/askpass.sh
    - name: Mirror to SourceForge
      run: |
          #mkdir ~/.ssh
          #ssh-keyscan $OWSFHOST > ~/.ssh/known_hosts
          export SSH_ASKPASS=$HOME/askpass.sh
          git push -v ssh://$OWSFUSER@$OWSFHOST/p/$OWSFREPO
      env:
        SSH_PASSWORD: ${{ secrets.OW_SF_TOKEN2 }}
        OWSFUSER:     ${{ secrets.OW_SF_TOKEN1 }}
        OWSFHOST:     git.code.sf.net
        OWSFREPO:     openwatcom/open-watcom-v2-test-jm
        DISPLAY:         :0
        GIT_SSH_COMMAND: "setsid ssh"
