name: WikiDocs

on: [push]

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - name: Build Bootstrap Tools
      run: |
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          cd $OWROOT
          mkdir $OWBINDIR
          # build OW wmake for host system
          cd $OWSRCDIR/wmake
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          make -f ../posmake TARGETDEF=-D__LINUX__
          # build OW builder for host system
          cd $OWSRCDIR/builder
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          $OWBINDIR/wmake -f ../binmake bootstrap=1 builder.exe
          # build OW tools for host system
          cd $OWSRCDIR/watcom
          builder boot
          cd $OWSRCDIR/builder
          builder boot
          cd $OWSRCDIR/whpcvt
          builder boot
          cd $OWSRCDIR/bmp2eps
          builder boot
          cd $OWROOT
      env:
        OWTOOLS: GCC
        OWROOT: $GITHUB_WORKSPACE
    - uses: actions/upload-artifact@master
      with:
        name: boot
        path: build/binbuild
  wikihtml:
    needs: boot
    runs-on: ubuntu-latest
    steps:
    - name: Install DOSBOX
      run: |
          pwd
          for i in {1..10}
          do
            sudo apt-get install -y dosbox
            if [ $? = 0 ]; then
              break
            fi
          done
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - run: mkdir build/binbuild
    - name: Load boot
      uses: actions/download-artifact@master
      with:
        name: boot
        path: build/binbuild
    - run: chmod +x build/binbuild/*
    - name: Build Wiki Documentation
      run: |
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          # build WIKI documentation
          cd $OWSRCDIR
          builder -i docs wikihtml .and wikihtml .or -- -- docset=wikihtml -i
          cd $OWROOT
          mkdir artifact
          cp docs/html/*.bmp artifact/
          cp docs/html/*.htm artifact/
      env:
        OWTOOLS: GCC
        OWGHOSTSCRIPTPATH: $PATH
        OWDOSBOXPATH: $PATH
        OWDOSBOX: dosbox
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
        SDL_DISKAUDIOFILE: /dev/null
    - uses: actions/upload-artifact@master
      with:
        name: wikihtml
        path: artifact
  wikipdf:
    needs: boot
    runs-on: ubuntu-latest
    steps:
    - name: Install DOSBOX
      run: |
          for i in {1..10}
          do
            sudo apt-get install -y dosbox
            if [ $? = 0 ]; then
              break
            fi
          done
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - run: mkdir build/binbuild
    - name: Load boot
      uses: actions/download-artifact@master
      with:
        name: boot
        path: build/binbuild
    - run: chmod +x build/binbuild/*
    - name: Build Wiki Documentation
      run: |
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          # build WIKI documentation
          cd $OWSRCDIR
          builder -i docs wikipdf .and wikipdf .or -- -- docset=wikipdf -i
          cd $OWROOT
          mkdir artifact
          cp docs/pdf/*.pdf artifact/
      env:
        OWTOOLS: GCC
        OWGHOSTSCRIPTPATH: $PATH
        OWDOSBOXPATH: $PATH
        OWDOSBOX: dosbox
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
        SDL_DISKAUDIOFILE: /dev/null
    - uses: actions/upload-artifact@master
      with:
        name: wikipdf
        path: artifact
  wikiupdate:
    needs: [wikihtml, wikipdf]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git User
      run: |
        git config --global user.email "openwatcomazure@gmail.com"
        git config --global user.name "Open Watcom Azure"
    - name: Prepare askpass script
      run: |
        echo "#!/bin/sh" > $HOME/askpass.sh
        echo "echo \"$SSH_PASSWORD\"" >> $HOME/askpass.sh
        chmod +x $HOME/askpass.sh
    - name: Load Wiki
      run: |
        mkdir wiki
        export SSH_ASKPASS=$HOME/askpass.sh
        git clone --depth=1 --branch=master https://$OWGHUSER@github.com/$OWWIKIPROJ.git wiki
      env:
        OWWIKIPROJ: jmalak/open-watcom-v2-webdocs
        OWGHUSER: ${{ secrets.OW_GH_TOKEN1 }}
        SSH_PASSWORD: ${{ secrets.OW_GH_TOKEN2 }}
    - run: mkdir docs
    - name: Load boot
      uses: actions/download-artifact@master
      with:
        name: wikihtml
        path: wiki/docs
    - name: Load boot
      uses: actions/download-artifact@master
      with:
        name: wikipdf
        path: wiki/docs
    - name: Update Wiki
      run: |
        export SSH_ASKPASS=$HOME/askpass.sh
        cd wiki
        git add -v -f .
        if [ -n "$(git status -uno --porcelain)" ]
        then
          git commit -v -m "Azure Pipelines build $(Build.BuildNumber)"
          git push -v
        fi
      env:
        SSH_PASSWORD: ${{ secrets.OW_GH_TOKEN2 }}
