name: WikiDocs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Bootstrap Tools
      run: |
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          cd $OWROOT
          mkdir $OWBINDIR
          # build OW wmake for host system
          cd $OWSRCDIR/wmake
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          make -f ../posmake TARGETDEF=-D__LINUX__
          # build OW builder for host system
          cd $OWSRCDIR/builder
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          $OWBINDIR/wmake -f ../binmake bootstrap=1 builder.exe
          # build OW tools for host system
          cd $OWSRCDIR/watcom
          builder boot
          cd $OWSRCDIR/builder
          builder boot
          cd $OWSRCDIR/whpcvt
          builder boot
          cd $OWSRCDIR/bmp2eps
          builder boot
          cd $OWROOT
      env:
        OWTOOLS: GCC
      
    - name: Build Wiki Documentation
      run: |
          for i in {1..10}
          do
            sudo apt-get install -y dosbox
            if [ $? = 0 ]; then
              break
            fi
          done
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          # build WIKI documentation
          cd $OWSRCDIR
          builder -i docs wikihtml .and wikihtml .or -- -- docset=wikihtml -i
          builder -i docs wikipdf .and wikipdf .or -- -- docset=wikipdf -i
          cd $OWROOT
      env:
        OWTOOLS: GCC
        OWGHOSTSCRIPTPATH: $PATH
        OWDOSBOXPATH: $PATH
        OWDOSBOX: dosbox
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
        SDL_DISKAUDIOFILE: /dev/null
