name: WikiDocs

on: [push]

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Bootstrap Tools
      run: |
          export OWROOT=$GITHUB_WORKSPACE
          . $OWROOT/cmnvars.sh
          cd $OWROOT
          mkdir $OWBINDIR
          # build OW wmake for host system
          cd $OWSRCDIR/wmake
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          make -f ../posmake TARGETDEF=-D__LINUX__
          # build OW builder for host system
          cd $OWSRCDIR/builder
          mkdir $OWOBJDIR
          cd $OWOBJDIR
          $OWBINDIR/wmake -f ../binmake bootstrap=1 builder.exe
          # build OW tools for host system
          cd $OWSRCDIR/watcom
          builder boot
          cd $OWSRCDIR/builder
          builder boot
          cd $OWSRCDIR/whpcvt
          builder boot
          cd $OWSRCDIR/bmp2eps
          builder boot
          cd $OWROOT
      env:
        OWTOOLS: GCC
    - uses: actions/upload-artifact@master
      with:
        name: boot
        path: $OWBINDIR
