name: WikiDocs

on: [push]

jobs:
  boot:
    runs-on: windows-latest
    steps:
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - name: Build Bootstrap Tools
      run: |
          set OWROOT=%GITHUB_WORKSPACE%
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          call %OWROOT%\cmnvars.bat
          set
          mkdir %OWBINDIR%
          REM build OW wmake for host system
          mkdir %OWSRCDIR%\wmake\%OWOBJDIR%
          cd %OWSRCDIR%\wmake\%OWOBJDIR%
          nmake -f ..\nmake
          REM build OW builder for host system
          mkdir %OWSRCDIR%\builder\%OWOBJDIR%
          cd %OWSRCDIR%\builder\%OWOBJDIR%
          %OWBINDIR%\wmake -f ..\binmake bootstrap=1 builder.exe
          REM build OW tools for host system
          cd %OWSRCDIR%\watcom
          builder boot
          cd %OWSRCDIR%\builder
          builder boot
          cd %OWSRCDIR%\whpcvt
          builder boot
          cd %OWSRCDIR%\bmp2eps
          builder boot
          cd %OWROOT%
      env:
        OWTOOLS: VISUALC
    - name: Save Build Tools Artifact
      uses: actions/upload-artifact@master
      with:
        name: boot
        path: build\binbuild
  wikihtml:
    needs: boot
    runs-on: windows-latest
    steps:
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - name: Create Build Tools subdirectory
      run: mkdir build\binbuild
    - name: Load Build Tools Artifact
      uses: actions/download-artifact@master
      with:
        name: boot
        path: build\binbuild
    - name: Build Wiki Documentation
      run: |
          set OWROOT=%GITHUB_WORKSPACE%
          set OWCIBIN=%OWROOT%\ci\bin64
          set OWDOSBOXPATH=%OWCIBIN%
          set OWGHOSTSCRIPTPATH=%OWCIBIN%
          set OWWIN95HC=%OWCIBIN%\hcrtf.exe
          set OWHHC=%OWCIBIN%\hhc.exe
          call %OWROOT%\cmnvars.bat
          set
          REM build WIKI documentation
          cd %OWSRCDIR%
          builder -i docs wikihtml .and wikihtml .or -- -- docset=wikihtml -i
          cd %OWROOT%
          mkdir artifact
          copy docs\html\*.bmp artifact\
          copy docs\html\*.htm artifact\
      env:
        OWTOOLS: VISUALC
        OWDOSBOX: dosbox.exe
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
        SDL_DISKAUDIOFILE: NUL
    - name: Save Html Documentation Artifact
      uses: actions/upload-artifact@master
      with:
        name: wikihtml
        path: artifact
  wikipdf:
    needs: boot
    runs-on: windows-latest
    steps:
    - name: GitHub Repo clone
      uses: actions/checkout@v1
    - name: Create Build Tools subdirectory
      run: mkdir build\binbuild
    - name: Load Build Tools Artifact
      uses: actions/download-artifact@master
      with:
        name: boot
        path: build\binbuild
    - name: Build Wiki Documentation
      run: |
          set OWROOT=%GITHUB_WORKSPACE%
          set OWCIBIN=%OWROOT%\ci\bin64
          set OWDOSBOXPATH=%OWCIBIN%
          set OWGHOSTSCRIPTPATH=%OWCIBIN%
          set OWWIN95HC=%OWCIBIN%\hcrtf.exe
          set OWHHC=%OWCIBIN%\hhc.exe
          call %OWROOT%\cmnvars.bat
          set
          REM build WIKI documentation
          cd %OWSRCDIR%
          builder -i docs wikipdf .and wikipdf .or -- -- docset=wikipdf -i
          cd %OWROOT%
          mkdir artifact
          copy docs\pdf\*.pdf artifact\
      env:
        OWTOOLS: VISUALC
        OWDOSBOX: dosbox
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
        SDL_DISKAUDIOFILE: NUL
    - name: Save PDF Documentation Artifact
      uses: actions/upload-artifact@master
      with:
        name: wikipdf
        path: artifact
  wikiupdate:
    needs: [wikihtml, wikipdf]
    runs-on: windows-latest
    steps:
    - name: Setup Git User
      run: |
        git config --global user.email "openwatcomazure@gmail.com"
        git config --global user.name "Open Watcom Azure"
    - name: Prepare askpass script
      run: |
        echo "echo \"\$SSH_PASSWORD\"" > %HOME%\askpass.cmd
    - name: Load Wiki Repo
      run: |
        set SSH_ASKPASS=%HOME%\askpass.cmd
        git clone --depth=1 --branch=master https://%OWGHUSER%@github.com/%OWWIKIPROJ%.git .
      env:
        OWWIKIPROJ: jmalak/open-watcom-v2-webdocs
        OWGHUSER: ${{ secrets.OW_GH_TOKEN1 }}
        SSH_PASSWORD: ${{ secrets.OW_GH_TOKEN2 }}
    - name: Create docs subdirectory
      run: if not exists docs\* mkdir docs
    - name: Load Html Documentation Artifact
      uses: actions/download-artifact@master
      with:
        name: wikihtml
        path: docs
    - name: Change files extension *.htm to *.html
      run: ren docs\*.htm *.html
    - name: Load PDF Documentation Artifact
      uses: actions/download-artifact@master
      with:
        name: wikipdf
        path: docs
    - name: Update Wiki Repo
      run: |
        set SSH_ASKPASS=%HOME%\askpass.cmd
        git add -v -f .
        git commit -v -m "GitHub Workflow build"
        git push -v
      env:
        SSH_PASSWORD: ${{ secrets.OW_GH_TOKEN2 }}
